---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-ngninx-service-monitor
  namespace: prometheus
  labels:
    app: ingress-nginx
    # name: ingress-nginx-controller-metrics
    namespace: ingress-nginx
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: prometheus
  namespaceSelector:
    matchNames:
    - logiq
  selector:
    matchLabels:
      app: ingress-nginx