# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: ingress-nginx-service-monitor
#   namespace: prometheus
#   labels:
#     app: ingress-nginx-service-monitor
#     namespace: prometheus
# spec:
#   endpoints:
#   - interval: 30s
#     path: /metrics
#     port: prometheus
#   namespaceSelector:
#     matchNames:
#     - ingress-nginx
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: ingress-nginx
