---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: activepieces
  namespace: activepieces
spec:
  interval: 10m
  chart:
    spec:
      chart: meyercharts/activepieces
      version: 0.1.6
      sourceRef:
        kind: HelmRepository
        name: activepieces
        namespace: flux-system
      interval: 10m
  values:
    db:
      type: SQLITE3
    # type: POSTGRES
    # host: <host>
    # port: 5432
    # username: <username>
    # password: <password>
    # database: <database>
    ingress:
      enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
      kubernetes.io/ingress.class: traefik
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host:
        paths:
          - path: /activepieces
            pathType: Prefix
    # tls: []
    #   - secretName: chart-example-tls
    #     hosts:
    #       - chart-example.local
