---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: examiner
  namespace: canary-demo
spec:
  releaseName: examiner
  chart:
    spec:
      chart: ./charts/examiner
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m
  values:
    configuration:
      ECHO_VALUE: ⛈ First Rollout 🤘
      SERVER_ERROR_RATE: 0
      REQUEST_DELAY: 100..250
    canary:
      enabled: false