---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: examiner
  namespace: canary-demo
spec:
  releaseName: examiner
  chart:
    spec:
      chart: ./charts/examiner
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m
  values:
    configuration:
      replicaCount: 1
      image:
        repository: quay.io/heubeck/examiner
        pullPolicy: IfNotPresent
        tag: "1.6.2"
      service:
        type: NodePort
        port: 80
      container:
        port: 8080
      configuration: 
          ECHO_VALUE: ⛈ ARGO Rockssss🤘
          SERVER_ERROR_RATE: 0
          REQUEST_DELAY: 100..250
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 5
        targetCPUUtilizationPercentage: 80