---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1m
  chart:
    spec:
      chart: keda
      version: 2.7.1
      sourceRef:
        kind: HelmRepository
        name: keda-core
        namespace: flux-system
      interval: 1m
  values:
   