---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1m
  chart:
    spec:
      chart: loki-distributed
      version: 39.6.0
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
      interval: 1m
  values:
   