---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: nats
spec:
  interval: 10m
  chart:
    spec:
      chart: nats
      version: 0.19.11
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
      interval: 10m
  values:
    installCRDs: true
    dashboard:
      enabled: false
    jetstream:
      enabled: true