---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-rollouts
  namespace: argo-rollouts
spec:
  interval: 10m
  chart:
    spec:
      chart: bitnami/nats
      version: 7.5.10
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  values:
    installCRDs: true
    dashboard:
      enabled: false