---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 39.6.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
    grafana:
      service:
        type: NodePort
        port: 30005
      adminUser: admin
      adminPassword: admin
      ingress:
        enabled: true
        hosts:
        - host: prometheus.local
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ include "name" . }}
                  port:
                    number: 80