---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-runner-2
  namespace: redis-runner-2
spec:
  releaseName: redis-runner
  chart:
    spec:
      chart: ./charts/redis-runner-dummy
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m
  values:
    triggers:
    - type: cron
      metadata:
        timezone: Europe/Berlin  # The acceptable values would be a value from the IANA Time Zone Database.
        start: '* * * * *'
        end: '45 * * * *'         # Every hour on the 45th minute
        desiredReplicas: "10"