---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  interval: 10m
  chart:
    spec:
      chart: docker-registry
      version: 2.2.2
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
      interval: 10m
  values:
    ingress:
      enabled: true
      className: "nginx"
      path: /
      hosts: 
        - docker-registry.test.local