---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unleash
  namespace: unleash
spec:
  interval: 1m
  chart:
    spec:
      chart: unleash
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: unleash
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      hosts: 
        - unleash.test.local
      path: /
      annotations:
        kubernetes.io/ingress.class: "nginx"