apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
