apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'rollout-bluegreen-preview-ingress'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: examiner-bg-preview.test.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rollout-bluegreen-preview
            port:
              number: 80