replicaCount: 1

image:
  repository: quay.io/heubeck/examiner
  pullPolicy: IfNotPresent
  tag: "1.6.2"

service:
  type: NodePort
  port: 80

container:
  port: 8080

configuration: 
    ECHO_VALUE: ⛈ MOBIKO Rockssss🤘
    SERVER_ERROR_RATE: 100
    REQUEST_DELAY: 100..250

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80