apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  # replicas: 5
  strategy:
    canary:
      analysis:
        templates:
        - templateName: httpsuccessrate
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
      - setWeight: 40
      - pause: {duration: 10s}
      - setWeight: 60
      - pause: {duration: 10s}
      - setWeight: 80
      - pause: {duration: 10s}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
        app: argotest123
  template:
    metadata:
      labels:
        app: argotest123
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ include "name" . }}
        ports:
          - name: http
            containerPort: {{ .Values.container.port }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /.well-known/live
            port: http
        readinessProbe:
          httpGet:
            path: /.well-known/ready
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}