apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ include "name" . }}-ingress'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: examiner.test.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "name" . }}
            port:
              number: 80